# Generated by Django 3.2.9 on 2022-02-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partypayment',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткий комментарий'),
        ),
        migrations.AlterField(
            model_name='partytransaction',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткий комментарий'),
        ),
    ]
