# Generated by Django 3.2.9 on 2022-02-03 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220203_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partypayment',
            options={'verbose_name': 'Расход на компанию', 'verbose_name_plural': 'Расходы на компанию'},
        ),
        migrations.AlterField(
            model_name='partygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='party_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='partypayment',
            name='debtors',
            field=models.ManyToManyField(blank=True, related_name='party_debtors', to=settings.AUTH_USER_MODEL, verbose_name='На кого делить расходы'),
        ),
    ]
