# Generated by Django 3.2.9 on 2022-02-13 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Компания/группа',
                'verbose_name_plural': 'Компании/группы',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('value', models.FloatField(verbose_name='Сумма перевода')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткий комментарий')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='party.party', verbose_name='Компания/группа')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Денежный перевод между участниками компании',
                'verbose_name_plural': 'Денежные переводы между участниками компании',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('price', models.FloatField(verbose_name='Сумма расходов')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткий комментарий')),
                ('debtors', models.ManyToManyField(blank=True, related_name='debtors', to=settings.AUTH_USER_MODEL, verbose_name='На кого делить расходы')),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Кто платил')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='party.party', verbose_name='Компания/группа')),
            ],
            options={
                'verbose_name': 'Расход на компанию',
                'verbose_name_plural': 'Расходы на компанию',
            },
        ),
    ]
