# Generated by Django 3.2.9 on 2022-02-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='investor',
            new_name='sponsor',
        ),
    ]
