# Generated by Django 4.1.13 on 2024-03-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_rename_investor_payment_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
