# Generated by Django 4.1.13 on 2024-03-09 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0004_alter_transaction_recipient_alter_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_parties', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debtors',
            field=models.ManyToManyField(related_name='debtors_payments', to=settings.AUTH_USER_MODEL, verbose_name='На кого делить расходы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_payments', to=settings.AUTH_USER_MODEL, verbose_name='Кто платил'),
        ),
    ]
