# Generated by Django 4.1.13 on 2024-03-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_alter_party_creator_alter_party_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Расход в компании', 'verbose_name_plural': 'Расходы в компании'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='party.party', verbose_name='Компания'),
        ),
    ]
