# Generated by Django 4.1.13 on 2024-03-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_alter_party_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='debtors',
            new_name='py_debtors',
        ),
    ]
