# Generated by Django 4.1.13 on 2024-03-10 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0007_rename_debtors_payment_py_debtors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to=settings.AUTH_USER_MODEL, verbose_name='Должник')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='party.payment', verbose_name='Расход')),
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники',
            },
        ),
    ]
