# Generated by Django 4.1.13 on 2024-03-10 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0008_debtors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debtors',
            new_name='Debt',
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='debt',
            new_name='debtor',
        ),
    ]
