# Generated by Django 4.1.13 on 2024-03-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_alter_debt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.FloatField(verbose_name='Сумма расхода'),
        ),
    ]
