# Generated by Django 4.1.13 on 2024-03-11 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0011_alter_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to=settings.AUTH_USER_MODEL, verbose_name='Должник'),
        ),
    ]
