# Generated by Django 4.1.13 on 2024-03-27 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0012_alter_debt_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.debt', verbose_name='Долг, по которому был сделан перевод'),
        ),
    ]
